### ISSUE TITLE
Sharing iP code quality feedback [for @WeeeHung] - Round 2

### ISSUE THREAD

**Issue by soc-se-script** [WeeeHung/ip#8]
@WeeeHung We did an automated analysis of your code to detect potential areas to improve the code quality. We are sharing the results below, so that you can avoid similar problems in your tP code (which will be graded more strictly for code quality).

IMPORTANT: Note that the script looked for **just a few easy-to-detect problems only**, and **at-most three example are given** i.e., there can be other areas/places to improve.

### Aspect: Tab Usage

No easy-to-detect issues :+1: 

### Aspect: Naming boolean variables/methods

No easy-to-detect issues :+1: 

### Aspect: Brace Style

No easy-to-detect issues :+1: 

### Aspect: Package Name Style

No easy-to-detect issues :+1: 

### Aspect: Class Name Style

No easy-to-detect issues :+1: 

### Aspect: Dead Code

Example from [`src/main/java/Duke.java` lines `37-37`](https://github.com/WeeeHung/ip/blob/fbea8e20d9ee047fbba82824a621d94346fea2ec/src/main/java/Duke.java#L37..L37):

```java

//        storage.loadListFromFile();

```

Example from [`src/main/java/Duke.java` lines `38-38`](https://github.com/WeeeHung/ip/blob/fbea8e20d9ee047fbba82824a621d94346fea2ec/src/main/java/Duke.java#L38..L38):

```java

//        ui.printIntro();

```

Example from [`src/main/java/Duke.java` lines `40-40`](https://github.com/WeeeHung/ip/blob/fbea8e20d9ee047fbba82824a621d94346fea2ec/src/main/java/Duke.java#L40..L40):

```java

//        while (true) {

``` 

**Suggestion:** Remove dead code from the codebase.

### Aspect: Method Length

No easy-to-detect issues :+1: 

### Aspect: Class size

No easy-to-detect issues :+1: 

### Aspect: Header Comments

Example from [`src/main/java/Duke.java` lines `17-24`](https://github.com/WeeeHung/ip/blob/fbea8e20d9ee047fbba82824a621d94346fea2ec/src/main/java/Duke.java#L17..L24):

```java

    /**
     * The main method that serves as the entry point for the Duke application.
     *
     * This method initializes key components of the Duke application, such as the storage and parser,
     * and handles the execution of user commands and interactions with the chatbot.
     *
     * @param args The command-line arguments passed to the application (not used in this application).
     */

``` 

**Suggestion:** Ensure method/class header comments follow the format specified in the coding standard, in particular, the phrasing of the overview statement.

### Aspect: Recent Git Commit Message

No easy-to-detect issues :+1: 

### Aspect: Binary files in repo

* [`iPBot-2.jar`](https://github.com/WeeeHung/ip/blob/fbea8e20d9ee047fbba82824a621d94346fea2ec/iPBot-2.jar) 
             

**Suggestion:** Avoid committing binary files (e.g., `*.class`, `*.jar`, `*.exe`) or third-party library files in to the repo.

----

:exclamation: You are not _required_ to (but you are welcome to) fix the above problems in your iP, unless you have been separately asked to resubmit the iP due to code quality issues.

:information_source: The bot account used to post this issue is un-manned. **Do not reply to this post** (as those replies will not be read). Instead, contact `cs2103@comp.nus.edu.sg` if you want to follow up on this post.

**Comment by WeeeHung** [comment]
Thanks for the feedback. The IP has been fixed according to the mentioned feedbacks. Issue closed.
